---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-jupyter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tf-jupyter
    spec:
      containers:
      - name: tensorflow
        image: swiftdiaries/dl-kopsjupyter
        ports:
        - containerPort: 8888
        resources:
          requests:
            alpha.kubernetes.io/nvidia-gpu: 2
            cpu: 24
          limits:
            alpha.kubernetes.io/nvidia-gpu: 2
            cpu: 24
        volumeMounts:
        - name: nvidia-driver-384-111
          mountPath: /usr/local/nvidia
          readOnly: true
        - name: libcuda-so
          mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
        - name: libcuda-so-1
          mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
        - name: libcuda-so-384-111
          mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.384.111
          readOnly: true
      volumes:
      - name: nvidia-driver-384-111
        hostPath:
          path: /usr/lib/nvidia-384
      - name: libcuda-so
        hostPath:
          path: /usr/lib/x86_64-linux-gnu/libcuda.so
      - name: libcuda-so-1
        hostPath:
          path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
      - name: libcuda-so-384-111
        hostPath:
          path: /usr/lib/x86_64-linux-gnu/libcuda.so.384.111
        
---
apiVersion: v1
kind: Service
metadata:
  name: tf-jupyter-service
  labels:
    app: tf-jupyter
spec:
  selector:
    app: tf-jupyter
  ports:
  - port: 8888
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer
---
